=== ATNF/cs-studio/applications/plugins/org.csstudio.alarm.treeView/ldapContentModel.dtd
<!ELEMENT root (efan*)>
<!ELEMENT efan (ecom* , eren*)>
<!ELEMENT ecom (ecom* , eren*)>
<!ELEMENT eren (#PCDATA)>

<!ATTLIST ou name CDATA #REQUIRED>
<!ATTLIST efan name CDATA #REQUIRED>
<!ATTLIST ecom name CDATA #REQUIRED>
<!ATTLIST eren name CDATA #REQUIRED>

=== ATNF/cs-studio/applications/plugins/org.csstudio.alarm.treeView/EpicsAlarmCfg.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE root SYSTEM "D:\development\bknerr\workspace\org.csstudio.alarm.treeView\ldapContentModel.dtd">
<root> 

      <efan name="FLASH">
        <ecom name="Batterie">
          <ecom name="Laderichter">
            <eren name="DE:K:WK:D1:24V_DC_Ugo_ogg"/>
            <eren name="DE:K:WK:D1:24V_DC_Ugo_tru"/>
          </ecom> 
          <eren name="DE:K:WK:D1:24V_DC_Uga_ugg"/>
        </ecom>
        <ecom name="tritratrullala">
        </ecom>
        
        <eren name="DE:K:WK:D1:24V_DC_Uga_ugg"/>
        <eren name="DE:K:WK:D1:24V_DC_Ug_mbbi"/>
      </efan>
      
      <efan name="Drehstromanlage">
        <ecom name="Batterie">
          <ecom name="Laderichter_2">
            <eren name="DE:K:WK:D1:bli"/>
            <eren name="DE:K:WK:D1:bla"/>
          </ecom> 
        </ecom>
      </efan>

</root>
